#!/bin/bash
# Regenerates assets/logos/logos.js from whatever image files are in assets/logos.
#
# Why this exists: Trackr is a static site, so the browser can't list a folder at runtime. This
# writes the list into a small script the app loads, which is how every logo in the folder shows
# up in the logo pickers and in Settings -> Logos & Images.
#
# Usage: drop a .png/.jpg/.svg/.webp into assets/logos/, then run:   bash tools/update-logos.sh
# The file name becomes the display name (underscores become spaces), and the app auto-applies it
# to any bank/broker/payee whose name matches — e.g. "Trade_Republic.png" for "Trade Republic".
cd "$(dirname "$0")/.." || exit 1
out=assets/logos/logos.js
{
  echo "/* GENERATED by tools/update-logos.sh — don't edit by hand; add images to this folder and re-run it. */"
  echo "window.LOCAL_LOGOS = ["
  for f in assets/logos/*.png assets/logos/*.jpg assets/logos/*.jpeg assets/logos/*.svg assets/logos/*.webp; do
    [ -e "$f" ] || continue
    base=$(basename "$f")
    name="${base%.*}"
    name="${name//_/ }"
    name=$(printf '%s' "$name" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf '  { name: "%s", file: "assets/logos/%s" },\n' "$name" "$base"
  done
  echo "];"
} > "$out"
echo "Wrote $out with $(grep -c 'file:' "$out") logo(s)."
